defaults:
  - override hydra/launcher: joblib
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: nsgaii

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: [minimize, minimize]
    study_name: multi-objective
    storage: null
    n_trials: 200
    n_jobs: 5
    params:
      wind_system_capacity: range(0, 30000, step=3000)
      solar_system_capacity: range(0, 40000, step=4000)
      battery_capacity: range(0, 45000, step=7500)

results_csv: ${hydra:runtime.cwd}/berkeley_results.csv

wind_system_capacity: 1500
solar_system_capacity: 1500
battery_capacity: 20000